### ISSUE TITLE
cant build with phonegap build

### ISSUE THREAD

**Issue by mrqaidi** [keosuofficial/cordova-audio-stream-plugin#9]
hello there is conflict with  org.apache.cordova.media

here is  logs

Build Date: 2015-12-25 18:34:51 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Installing "org.apache.cordova.media" for android
Installing "org.apache.cordova.statusbar" for android
Installing "org.apache.cordova.device" for android
Installing "de.appplant.cordova.plugin.background-mode" for android
Installing "com.indigoway.cordova.whitelist.WhitelistPlugin" for android
"plugman install --platform android --project /project --plugin /gimlet/var/plugins/b8e8276e-4e9d-11e5-889e-22000b954cd4": Installing "com.keosu.cordova.stream" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.keosu.cordova.stream':Error: Uh oh!
"/project/src/org/apache/cordova/media/AudioHandler.java" already exists!
    at Object.module.exports.common.copyNewFile (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/platforms/common.js:67:19)
    at Object.module.exports.source-file.install (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/platforms/android.js:78:20)
    at installWrapper (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:576:20)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:368:24
    at _fulfilled (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44
Uh oh!
"/project/src/org/apache/cordova/media/AudioHandler.java" already exists!

**Comment by alisonmonteiro** [comment]
Same issue here
